server:
  port: 8010
spring:
  application:
    name: movieticketing-consumer-movie
#eureka:
# client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true