server:
  port: 8010

spring:
  application:
    name: movieticketing-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://libingbin2015@aliyun.com:libingbin2015@aliyun.com@peer1:8761/eureka/,http://libingbin2015@aliyun.com:libingbin2015@aliyun.com@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

#使用属性自定义的方式配置Ribbon
#microservice-provider-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#使用属性自定义的方式配置Feign日志
#logging:
#  level:
#    com.bingbinlee.springcloud.micro.user.feign.UserFeignClientLogging: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。